# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor_A = torch.rand(7, 7)
random_tensor_A

tensor([[4.7004e-01, 5.2699e-01, 7.7130e-01, 9.0566e-01, 8.5392e-01, 4.1100e-01,
         3.2720e-01],
        [9.9476e-01, 1.6442e-01, 3.4441e-01, 6.6717e-01, 1.3654e-01, 6.9687e-01,
         6.1959e-01],
        [4.0701e-02, 8.3317e-01, 8.1038e-01, 3.8525e-01, 4.7363e-02, 1.5253e-01,
         5.4621e-01],
        [6.1212e-01, 4.0374e-01, 1.9248e-01, 5.7478e-01, 9.1493e-04, 2.6125e-01,
         2.2272e-01],
        [9.2791e-01, 9.5153e-01, 6.5839e-01, 8.7473e-01, 7.4991e-01, 6.5618e-02,
         2.0782e-01],
        [1.6041e-01, 4.4517e-01, 6.0030e-03, 8.6949e-01, 4.6813e-01, 2.1638e-01,
         3.6110e-01],
        [7.1422e-01, 1.4802e-01, 2.8667e-01, 3.7175e-01, 1.7200e-01, 5.3214e-01,
         6.1974e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_B = torch.rand(1, 7).T
# Perform matrix multiplication
mult = torch.matmul(random_tensor_A, random_tensor_B)
mult

tensor([[3.2561],
        [2.4000],
        [1.9676],
        [1.5961],
        [3.4740],
        [1.7788],
        [1.8245]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
MANUAL_SEED = 0

# Create two random tensors
torch.manual_seed(MANUAL_SEED)
random_tensor_A = torch.rand(7, 7)
torch.manual_seed(MANUAL_SEED)
random_tensor_B = torch.rand(1, 7).T
# Matrix multiply tensors

mult = torch.matmul(random_tensor_A, random_tensor_B)
mult, mult.shape


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available else "cpu"
print(torch.cuda.is_available())
# Create two random tensors on GPU
random_tensor_A = torch.rand(2, 3).to(device)
random_tensor_B = torch.rand(2, 3).to(device)
random_tensor_A, random_tensor_B

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
random_tensor_B_T = random_tensor_B.T
matmult = torch.matmul(random_tensor_A, random_tensor_B_T)
matmult

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
maximum = torch.max(matmult)
# Find min
minimum = torch.min(matmult)

maximum, minimum

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
arg_max = torch.argmax(matmult)

# Find arg min
arg_min = torch.argmin(matmult)

arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)
# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor)
squuezed_tensor.shape
# Print out tensors and their shapes
