In [ ]:
import numpy
import pandas
import matplotlib.pyplot as plt
import torch

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])

In [ ]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
###Random tensors

###Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers to better represent the data.

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7956, 0.4396, 0.0340, 0.7894],
        [0.3435, 0.9413, 0.7870, 0.2124],
        [0.7021, 0.0240, 0.5865, 0.4701]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(3, 4)

tensor([[0.2135, 0.9215, 0.9097, 0.6155],
        [0.1259, 0.1288, 0.2466, 0.4656],
        [0.4579, 0.2619, 0.5558, 0.4993]])

In [ ]:
#Create a tensors of zeros and ones

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#Creating a range od tensors and tensor-like

torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeors = torch.zeros_like(input = one_to_ten)
ten_zeors

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Tensor datatype
#Float 32 tensor

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=False)

print(float_32_tensor)

tensor([3., 6., 9.])


In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Getting information from tensors

# To get Tensor datatype use 'tensor.dtype'
# To get Tensor shpae use 'tensor.shape'
# To get Tensor device use "tensor.device"

In [ ]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1612, 0.3638, 0.5800, 0.2809],
        [0.7357, 0.9623, 0.8590, 0.4162],
        [0.6260, 0.3075, 0.2625, 0.8862]])

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1612, 0.3638, 0.5800, 0.2809],
        [0.7357, 0.9623, 0.8590, 0.4162],
        [0.6260, 0.3075, 0.2625, 0.8862]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
#Manipulating tensors

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 715 µs, sys: 113 µs, total: 828 µs
Wall time: 2.81 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 79 µs, sys: 0 ns, total: 79 µs
Wall time: 47.4 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 4))

tensor([[2.3127, 2.1393, 2.2477, 2.6994],
        [2.8965, 2.4891, 2.3262, 2.8701],
        [2.3335, 2.4400, 2.6619, 2.2979]])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B_T = tensor_B.T

In [ ]:
torch.matmul(tensor_A, tensor_B_T)

In [ ]:
#Finding the min, max, sum, etc(tensor aggregation)

x = torch.arange(0, 100, 10)
x

In [ ]:
torch.max(x), x.max()

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
torch.sum(x), x.sum()

In [ ]:
# Finding the positional min and max

x.argmin()

In [ ]:
x.argmax()

In [ ]:
x

In [ ]:
#Reshaping, stacking, squeezing and unsqueezing tensors

import torch
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

In [ ]:

z = x.view(1, 9)
z, z.shape

In [ ]:
z[:, 0]=5
z, x

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

In [ ]:
x_reshaped

In [ ]:
x_reshaped.shape

In [ ]:
x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().shape

In [ ]:
y = torch.tensor([1, 2, 3])

In [ ]:
y

In [ ]:
y.shape

In [ ]:
z = y.unsqueeze(dim=0)

In [ ]:
z.shape

In [ ]:
z

In [ ]:
w = y.unsqueeze(dim=2)

In [ ]:
w

In [ ]:
w.shape

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_original

In [ ]:
x_permuted = x_original.permute(2, 0, 1)

In [ ]:
x_permuted.shape

In [ ]:
x_original.shape

In [ ]:
x_permuted

In [ ]:
x_original[0, 0, 0]=728212
x_original[0, 0, 0], x_permuted[0, 0, 0]

In [ ]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
arrayy = array + 1
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3746, 0.1206, 0.8894, 0.9813],
        [0.4975, 0.3681, 0.6435, 0.7249],
        [0.7431, 0.5296, 0.7039, 0.4596]])
tensor([[0.4168, 0.1759, 0.5391, 0.8211],
        [0.7078, 0.6438, 0.5460, 0.6124],
        [0.1845, 0.6389, 0.1197, 0.7844]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
 import torch

 torch.cuda.is_available()


True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Create a tensor

tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')